spring.application.name=AIService


server.port=8080

# set the value form command-line argument
spring.ai.openai.api-key=${OPEN_AI_KEY}
spring.ai.openai.chat.options.model=gpt-4.1
spring.ai.openai.chat.options.temperature=0.2
spring.ai.openai.chat.options.max-tokens=200

#spring.ai.ollama.base-url=http://localhost:11434
#
#spring.ai.ollama.chat.model=codellama:latest
#spring.ai.ollama.model.chat.options.temperature=0.7
#spring.ai.ollama.model.chat.options.max-tokens=2048

#logging.level.org.springframework.ai.chat.client.advisor=DEBUG
#logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG

# 1. Turn on prompt and completion recording
spring.ai.chat.observations.log-prompt=true
spring.ai.chat.observations.log-completion=true

# 2. Tell Spring to print these observations to your console
logging.level.org.springframework.ai.chat.observation=DEBUG

#mongoDB config
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=chatApp

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO